### PR TITLE
Cfgfiles

### PR DESCRIPTION
**Pull request by paukstelis**
I'm sorry this is not very clean. I wanted to get the request put in before I get busy for holidays. 
This pull request contains the basic for getting Prusa MMU working with filaswitch and S3D.
Changes include some modifications to avoid extra extrusions when using multiple profiles in S3D, the addition of cooling steps after retraction which also serves as a wipe step, and the first attempt at creating a pre-print prime for each extruder (in reverse order).

### CODE REVIEW

**Comment by spegelius** [comment]
After a quick look looks good. You'll just need to rebase to use the latest changes from cfgfiles and remove a couple of commits from between that seem to be cherry-pics or something? I'll also run some tests, but that'll have to wait after christmas etc. wont be near my printers during that time...

**Comment by paukstelis** [comment]
As a git noob, I think I've badly messed this up (rebasing). I should have read up some more before making this pull request. Sorry about that. I think I may need to just re-fork and clean up everything and add my commits. Just not that well versed in collaborative projects on git.

**Comment by spegelius** [comment]
That's ok, git does need some getting used to. I've never used github that much myself, we have Gerrit at work which would make rebasing etc. easier.
But anyhow, you could try rebasing with git pull:
git pull git@github.com:spegelius/filaswitch.git cfgfiles --rebase
This should use my cfgfiles branch as base and add you commits on top of it, one by one. In case of conflicts, you can either resolve them or skip a commit altogether

**Comment by paukstelis** [comment]
I tried rebasing, and I think I mostly got things right. I just missed removing my comment removal on some of the hdwcfg files and for some reason I borked up the conflict with slicer_simplify3d.py and couldn't figure out how to cleanly get back. I just put in a new commit with my one change (comment out the removal of tool 0). Clearly, I have a lot of learning to do with git.

**Comment by spegelius** [comment]
I'll try to go over this this week or weekend. Currently some other stuff taking my time, but I'd like to get this tested and merged

**Comment by spegelius** [comment]
Went through the code and looks good to me, thanks. Haven't tested yet, but I'll be doing that next. Interested to see if the Prusa additions have positive effect on Prometheus setup. I did compile modified version of Prusa MMU Slic3r a while back and it worked, but didn't see too much need for the extra movements etc.
The nozzle priming feature is also nice addition, need to test it. Previously expecting T0 to be loaded was kind of ambiguous...

**Comment by spegelius** [comment]
Ok been testing the code and doing test prints. I've done quite a lot of changes especially to the add_tool_change_gcode-function, found a bug with retractions (new S3D handles things differently). Also rewrote some of your code (I'll probably refactor the logic quite a lot at some point). But anyways, if you can test it, report if there's new bugs...

**Comment by paukstelis** [comment]
Hmm...just pulled and tested with a couple previous gcode files:

> 2018-01-16 13:39:51,875 - filaswitch - ERROR - Gcode processing failed: 'SwitchTower' object has no attribute 'z_offset'
Traceback (most recent call last):
  File "./filaswitch.py", line 132, in load_file
    result_file = pf.process(gcode_file)
  File "/home/paul/filaswitch/slicer_simplify3d.py", line 56, in process
    self.find_tower_position()
  File "/home/paul/filaswitch/gcode_file.py", line 192, in find_tower_position
    self.switch_tower.find_tower_position(x_max, x_min, y_max, y_min)
  File "/home/paul/filaswitch/switch_tower.py", line 340, in find_tower_position
    self.initialize_slots()
  File "/home/paul/filaswitch/switch_tower.py", line 99, in initialize_slots
    self.slots[i]['last_z'] = self.z_offset
AttributeError: 'SwitchTower' object has no attribute 'z_offset'

>

**Comment by spegelius** [comment]
Just pushed a fix to it, was merging changes from master and something didn't come through properly

**Comment by paukstelis** [comment]
Printing will have to wait till tomorrow, but gcode seems to be generating fine when comparing to the old. Looks like you fixed a few things that were causing me grief and simply didn't notice (moving z-close at the start; I was having to constantly adjust my live z-offset!). I do find that there is one double retraction right at the start:

> M83; relative E
G92 E0; reset extruder
G1 E-4.2000 F3000; retract
;PRIME END
; START SCRIPT END
G1 E-4.2000 F3000
G1 Z0.690 F720
>

In my case, this additional retraction that gets added at line 164 of preprime is not needed.

**Comment by spegelius** [comment]
Ah yes, preprime doesn't seem to actually need retraction. Removed.
Great, I actually unearthed some old bugs that were partly due to the way gocde was generated every which way in different parts of the code. Now all gcode should be generated in gcode.py so results should be more consistent. Also some retraction and prime bugs should be fixed now

**Comment by paukstelis** [comment]
Got a chance to print today. One thing I noticed is that I have significant feed rate differences between extruders on the wipe tower. It doesn't seem like that should happen. This shouldn't be from slicer settings (at least not directly) since they are just copied profiles. You can see it alternating in the wipe tower here:
screenshot from 2018-01-17 18-18-16

**Comment by paukstelis** [comment]
I see now that purge speeds are being generated dynamically based on the last outer perimeter speed. There cases where that could be useful, but it is clearly an issue here. Should it just be something that can be flagged in the hw_configs?

**Comment by spegelius** [comment]
That logic is something I did quite early in the filaswitch development. Iǘe been thinking about removing that feature as I don't think that itś necessary to slow tower printing down. Maybe only print the last tower perimeter slow to equalize the nozzle pressure with the layer...

**Comment by spegelius** [comment]
Also one thing that might need some tweaking is compensating the layers that are slowed down by S3D; printing tower will add to layer print time so there isn't that much need for slowdowns. So either make sure the S3D profile is set to slow down only real quick layers or do it in filaswitch (which would need some work to detect slowed down layers and calculating the updated speed values based on how long the tower takes...)

**Comment by paukstelis** [comment]
I'm leaving comments here since I continue to use the cfgfiles branch with PRUSAMMU.

I am finding a couple of instances with un-corrected retractions. I have a retraction just prior to starting the tower raft, but there is re-priming:

> G1 X136.996 Y80.374 E0.0088
> G1 E-4.2000 F3000
> G1 X136.996 Y80.589 F3600
> G1 X137.204 Y80.913 F3600
> G1 Z0.690 F720
> ; process Process1
> ; TOWER RAFT START
> G1 Z5.1900 F720; move z close
> G1 X97.308 Y126.033 F6000; move to raft zone
> G1 Z0.1900 F720; move z close
> G91; relative positioning
> G1 X54.800 Y0 E1.8011 F1800; raft wall
> G1 X0 Y55.900 E1.8372 F1800; raft wall
> G1 X-54.800 Y0 E1.8011 F1800; raft wall

Not sure if the change of Process is the culprit. The other one I believe is a S3D problem because I see it in the original file as well as when processed through filaswitch.

**Comment by spegelius** [comment]
Raft prime I'll need to fix, currently there's no check for it. Leftovers from the time when raft was always printed first.
S3D retractions need to be analysed if they are just something that's in the settings, like minimum travel before retract...

**Comment by spegelius** [comment]
Pushed some fixes to cfgfiles:
- raft prime, retracts
- purge speeds normalized
- optimize tower wall positions
I'll be merging this to master if nothing major comes up.

**Comment by paukstelis** [comment]
That's great. I actually just made a video on how to use S3D with filaswtich for PRUSAMMU, but it will probably be easier to show once it gets pushed into master. The only other change I would recommend would be to delete the existing .fff in hw_configurations. It could be removed all together, or I have an updated profile that would be a better beginning base line than the one that is there now.

**Comment by spegelius** [comment]
Ok great. The .fff profile can be updated with new version, send it to me or create pull request. I'll add couple profiles for Prometheus systems too. I'll probably move the files to profiles-dir, though.

**Comment by laird** [comment]
Shouldn’t the purge speed be as fast as possible, since the only goal is pushing out plastic, not print quality? Would it make sense to force it to a config parameter (e.g. 200 mm/s) instead of having anything to do with the input gcode?

**Comment by spegelius** [comment]
Yep, I'm actually looking into bumping up that speed. Config parameter should work fine

**Comment by spegelius** [comment]
Ok, I bumped the max purge speed to 3600 or 60mm/s for now. I'll add a configure option later if it's needed, but I think 60mm/s is a good  value for now.
Also modified the infill and wall print speeds somewhat, should be bit faster.
Added Prometheus .fff files and moved Prusa .fff to Simplify3D_profiles. Need to update README. Prints looking good and whole setup working very consistently. Release imminent.

**Pull request merged**
